[gcp]
type = "service_account"
project_id = "medadhdata2025"
private_key_id = "977f859dcb419919d25ff0406a7e2e56f5decf9f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDTF2jqx7Kd8FmA
MzA5tdgnXcH26rrg7hFIxkEhLPM9ZtnhML5aUI10EwUI3BAvFs3fEcbmjLGQABEB
Qixkchyp8CL0Tc/Fn55uyZBRe48YWazrdJNwEEpG/6hblIy/0ZlgyJswW/Zs42nJ
18DA3C+zCkVHoElKjlyUuVHoYnG/nGYKHdX8b+OvAishhAqrw7+nd6/2TPL+GZsL
zJOIHw7O7gxx05qAMaFpqpwHowj25+WvLWDcrKTaX+TwiN0uxv1xG4EngzZ6uAa4
6W9x3e0uktdy8utFZvYlw6Ncrh3YPvAOycVTB77tLKpIjZ6bECbmQjAjw6cmVOnK
ktP8jfTjAgMBAAECggEAHlvsDXQqFrf2D0+NXIdwLn04A7yPowDqQHau8EgINakA
pff+MHwMVAjWPQd1VmhntHDYk9jhQq4XxAAR5WJaCADO7ibwvmHuBc38cROdqWlg
Sr7J46CcJijnvEAZnA7XiclgNGzNfKyaTtq2UKZ6P7w26Y2+bLgbzZH3mz3pUR64
uDH0MAxYDLaO+M7QwHsQt19HdJPIXOtQ2oH2/7KXyXH18qKhK9qGf2q4yWYm15JL
GuKsbYi7zQRzoM4eoq2wb1C6HcQ7deTjIO3tbrpmNBTMpoOJpUiI66BXVsiF0pf7
e8L9aTTWwWYhkAWxT4p42H2/caR41o8H7YFg7jjWlQKBgQD3ndx0zscqpOfefmOU
9VIZGGNCZSue18/i6gHTAgj6tRwvYQg2M9w0RTueRPeA3w9/1XzptOn3jUYSpkvv
JynHfG7cbCqQr2sTnHn56bctz77YF48tQ465RwVyTrvGDTwSXpN5hJ0bO2LF/a30
wVSvTaSht2vdtjje912+FNE3lQKBgQDaPPpitn37uu1l9E0jEbin8h7EZwnrCJHW
EUiPBQSIiUryhQnrkiFnmmmGx/tIDninHKHNzggk4aXJ1g2F44lMlIkv/yt5SdhI
HUoXF037h/naTT9ewruQgYxyx3ghy4hUdDcwDoIbZbct6A6uvyJ2XIHM2rKgDutz
6FD0LtJ8lwKBgDOXobJ4zwi0mVdDcE4+Gx/9c9kGqWMMRlVaOo0TlHlgOQIqLoLU
pWICttxQNF2WnG0fN0qelk0tE1eZbKLkvxDAfXzR0MCavC224bdPmgoiifoOVpew
xtEV2i2p9/fZFBYjvIiKOA3PftIP/CnOCm4IOHA1fnUQnaLfWZncTodNAoGAbWuj
crjjI8LOYo8B2fJ5riMUUA8FhwVN8ZHK2oJ+imKj5ELV/XnQK9zcygocsD0pO0h8
y+5gYPWOJUugjh/OaEoVGq6Kwo5G1alxy3AQ1muP12dhvYZPep2pqKbgUbl1yjpW
rU6o50mxdV/jdLQ6eDPblLWWV/ADF6NEa5nKSVMCgYAXExWmbHuKObR6VevVNV9h
inccOPb+upsszFnrF+3qURkhaTi+DZqELjw9b5HUAxIBV9kkW11fZF+cRcLAgrlf
XK35Gh/FrGyNvuKU/qAqU0K8+d4dS3ML+gCyjDGLtCa3wkE1s0/20K2mqe06hrms
WKbqn3Vjri6af08BHPE17Q==
-----END PRIVATE KEY-----
"""
client_email = "vieweronly@medadhdata2025.iam.gserviceaccount.com"
client_id = "105920344946812164904"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vieweronly%40medadhdata2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

