type = "service_account"
project_id = "medadhdata2025"
private_key_id = "6e124598af28169154da7d4b4b3abb0c159f1b47"
private_key = """

MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIeCjnH0vj/BOR
geFivC+FwUwhUL4zXdUDzqS/PgIQ6eh1ljwKgFs5U4Yt3YZAKxH2CUISDJDUiNaE
fWK8VX+ZdzCtRU/jqRcFsqgnBlr05Zm1ab343BgPBhE8QrdfWJsOHkJ+H2Eum5sg
RHQ1IUgPZjqqhWutV2TvUjKlN3gscTg//6TTcpHmXfbdvqc5afH73zirLo1l7F+0
DRGa0P18b/FflBGrD3z6AZOt2k5LNiUen4uaxpTkQT3/xo+xb6xTsbe6byDePydJ
ktl18qkSPhycStSZozaMscSaptjdgmnliKPtQmH+59l/sXGAEtyVk5d1oMCvCIgY
94eOBYzNAgMBAAECggEACYRU0sYUVP4wUqHTGJwc+HFZAyLhaLBdbrkWbqLLt9BW
8hAgCRKXYhUSQ2anGzBAQckmOxOgI4rcfj0ynQTFEjzLkYo/FOx/1Iwq+fFOC57D
yY47z87pEHuGAXGcYXkkIUsz9mdYdn06I9HEH4qVMG/2vIYperjxqH/jOh80RA3F
W2iBcpFAH2J0MCpLMuy8IWycQN43yPRDzsIrrleDfKF6wq9x/P+MIjV4YklRCN2L
Zsp/B8QotpprrbNwruPRj9pxvwuirBFqNdSDRghtz/lWzQ1tz/gqNFNSLiwGvSXZ
T4J1sJfry+eipni8b/gWeaxnnXftw6eBsa7wJh0bQQKBgQD2ToSkASWHLveEgqmK
gG6OAfuBlPIwMgcJePeS1wCYJNZe8Bg9l10Ym+so7tWjdb/Y/+0EVdXZKHspr5ne
JS404R20JHPRkX71bmuP3i5GA0tOnyV6FvxV/MQvuwQV1SVdSN4FnO6myx3XFW82
DPHI8L1PI2Jmll6kOkkHRaAGwQKBgQDQW9dgbV2gat8gvibLHzkObkx8m08M0c/B
5RnccSVN8Q8Em9uhrxAe+5EcyIvkWsXnYQuyGJhnvjsvRWgMi5OmVY18JoUSuTY/
H9x2yFFEOy7jmMi3EME7+nXsIl6+FNexrnAO7tWU1QF7yvhUclMrphTFxUpy5cU9
pP22HI91DQKBgQDzQFBW+Jrri0MAJ1rxYi3NKcAOFd+qIX45qLI43wXDPH5KfKw0
B8z1hOcWIenz6VJzKS4XXf443XXlkXtQnT+pEbqYMnf/vMW59jdcen0QwCgbmakV
jqXe9id7TCOYvEyOeGxs9rPrHiZ2SMDwjJAtdzQ/eB6yWkdVwgplmCmXAQKBgQCB
oLHlPwVh2TuKPmMaOgmgTcTuPR24JwxvYB5vxEDmNdQXFPRWqfiInhBQ7QADiOnZ
IspI+f5PhM2DglXSgD/S2yUUGU7vMCVsrmDV0Zilr4BjftlY82aU7yTQTS3Oal8r
HxB+ad6dIswyfTt0JlBSNphz1mOUChllWbGyzCAAPQKBgBR+XGPbCCTqcWxeSZ3z
R7ujPrB5oI5L9sAR8EzWqJeksyFTR0pKaxlRjxfTLUpw+skbYMKmZuqCuBvY4VHa
6UMC4rN9L5HqcJB/0NIEMgW7Fc7e70aIMf5OPODTZfxyx02SB8R1kHqucY+ZzmAY
WjlZdymfS3fDZOaT1bJUlHaV

"""
client_email = "med-adh-data-app@medadhdata2025.iam.gserviceaccount.com"
client_id = "106237631518245861228"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/med-adh-data-app%40medadhdata2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
