type = "service_account"
project_id = "medadhdata2025"
private_key_id = "ce0f2b2ff8246de7d2ec9e2d7a379f87e3d53e0e"
private_key ="MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC3MM8D7kK70Bjb
NvcFLf1m4R3nyGupNiOCOXwm8fGR4G1X46DkofUkOsSl5ZDA58uHNZ7s9F6c3ttm
qHBfZBSYqHqtonK2sDwtJ79nkoazot1iIOfn/n02hqQfwYnaMwAFAPlAiZ8tbIAL
QrKEMh6UVuvtzaAGG5JBenl/2rKDGG5lfYSTV5Ab+Fa/ECNalv55x6yflPfdlLO5
QkUfcmXWo1Ei7Se9dBA5sc+hajl8QCh/pNqyPSMfn6SR5bQjHaAn2dobWiiIJZAb
RGsQFP14yiwfFfeJeR1I/WPGmG6pojXEjf945T0Iy44LK9Q+dfWc4J6AQKxEf//x
MkcYJa51AgMBAAECggEAUIWkyT6GmNV8x4beh6lSdFFJeuNu518Dtq8b8mZw38U9
at+EjlreTUGDxMQmn5SDsvgP1moH2H5hBDvPwS5Vm1CbNA1uzPykRtjs2lLe4MEa
/JIoPaJwWXJPXCIPPRkjzg9CgGq9zBKgKdL0cwUwydV3OP0kdOrTm/KAy4FO7C4l
JPsdjNjdNOTAcpRnlapJ2uhexvyUI7V1rd6axWc2kIcXxoCdKA32vWzWETJGasTr
etPr3ScWGc3OWBAV1a2qJ/S5iiIUU8HdNEUqu84hM3TeO6sI7X+3iQYcr6yXd/ks
6JXvJAR36sdkrz7m/sw1K0AIMzS1kUN8+NtdfX2vlQKBgQD+bhZsMENecimD+m1b
Rq3HFYPsCnsSdQl+7c6F6CmXwNtUljF5J7m3qBfuAMeKFt5HfwBJgoAnpyrJ0xx8
ZjWmq2YKz880aYmX1Sa3kcOiptwkFamFNUy+y7MnjsF1cBxadymfe6f/9fbQMxMp
8IUaaqGKCOtfA/0H5WeARx3hRwKBgQC4Ui/uPNOj7BFWYvIDoItr1JvSkytpJs2m
G0LmWBps634HSdtm2GLd6SFYpavVQMrtPeU/W1iIihjyVPD1yF/d7EHjemWiViHA
QDG0hAGq24ttUGiOzBE81Ct2iysKbKR7OuHnBgOOLjeX6zTcVuNScXb9wikHtGcm
wGu2UvPwYwKBgQCeWzqNf8SOhhOc10M1KlqCrLt9MFDFfh64555A7ezlTN22WfzU
4YrP6klqkwWexvj2Gu+80QKeq4cQMttp+duursNGO21Fu+ItpDcCzjCrjZs6wljO
Vgw8PGB3YHy8cVjUXZKEdtxrjVVe5EsrMU5G0NNWLJMCgmL8hSXUS28nhQKBgQCE
Zx1hEDajSL9Hg7n/WwLryYTJZchIN4SALpMG7gDFfwA/8hD1triGWaIHkLJ3dJyQ
gOa9dTuKkVDMOrIAjBg5TS4jXtfFHgQOms5Zsn2UIzLrqlgBQ5uaS3qRI/Ud/t7E
Wo7NqidBqfdrXJzTLmMK5NCqBh/9Fd0HHDADf2EVqwKBgQDJ46/99e34hGGjFsLg
ru8shhLYz0yYujowN/e470ROtcG0qNpy9Cr/w3Sy/Q0UOhgt+DJQM4dlqFc0sxmu
DNfPSLIFbv1XQ7XeRpU7ZyfilNVDz3iF4vCzL6tukLWcv91Rasq/GSJCvOT4ZPC7
C9QJnmPm11+wrq1SEBfAT+0sHw"

client_email = "newmedadhkey@medadhdata2025.iam.gserviceaccount.com"
client_id = "102258494300152959977"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/newmedadhkey%40medadhdata2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
